/// Identifiers for language-dependent matching rules supplied by the application.
public enum DNeuralUltrasoundDictationLocalizationKey: String, CaseIterable, Sendable {
    case absentComplaintFact
    case absentComplaintQuote
    case bilateralSide
    case birthDateFact
    case birthDateTrailingCue
    case birthEvidence
    case citedIdentifierPrefix
    case clinicalMeasurement
    case clinicalTextInComplaint
    case compactBirthFact
    case complaintAlias
    case complaintCue
    case complaintObservationBoundary
    case descriptionBoundary
    case descriptionMilliliter
    case descriptionMillimeter
    case descriptionUnits
    case descriptionVelocity
    case directHeightCue
    case directMeasurementSuffix
    case directWeightCue
    case discourseCorrection
    case examinationDescriptionLabel
    case examinationNumberLabel
    case femaleEvidence
    case femaleValue
    case fetalCue
    case followingCorrection
    case followingFetalCue
    case followingMeasurementField
    case followingPatientCue
    case followingRecordBoundary
    case gramValue
    case heightAlias
    case heightAliasPrefix
    case heightEvidenceCue
    case heightFactCue
    case heightFactUnits
    case heightUnits
    case identifierCue
    case identifierDigit
    case identifierValuePrefix
    case identifierValueSuffix
    case inWeightFact
    case isoBirthFact
    case leadingSpokenZero
    case leftSide
    case maleEvidence
    case maleValue
    case measurementCue
    case meterValue
    case missingComplaintBoundary
    case motherCue
    case namedBirthFact
    case naturalLanguagePatientCue
    case negation
    case negativeLabelPrefix
    case noComplaintsValue
    case numericCorrectionConnector
    case numericCorrectionUnits
    case numericSelfCorrection
    case observationCue
    case observationFraming
    case observationValueBoundary
    case patientBirthDateLabel
    case patientComplaintsLabel
    case patientGenderLabel
    case patientHeightLabel
    case patientIdentityQuote
    case patientNameCue
    case patientNameLabel
    case patientWeightLabel
    case profileExaminationNumber
    case profileGender
    case profileHeight
    case profileNoComplaints
    case profilePatientComplaints
    case profilePatientDateOfBirth
    case profilePatientGender
    case profilePatientHeightCM
    case profilePatientName
    case profilePatientWeightKG
    case profileWeight
    case recordCue
    case reportCue
    case rightSide
    case sideCorrection
    case spokenBirthCue
    case spokenIdentifierPrefix
    case spokenNumberWord
    case tallFactCue
    case tallFactUnits
    case trailingDescriptionFalseStart
    case ultrasoundWord
    case uncertainty
    case unfinishedDescription
    case unitCentimeter
    case unitGram
    case unitKilogram
    case unitLiter
    case unitMeter
    case unitMilliliter
    case unitMillimeter
    case unitPercent
    case unlabeledGender
    case unsupportedEmptyComplaint
    case verbalDate
    case weightAlias
    case weightAliasPrefix
    case weightEvidenceCue
    case weightFactCue
    case weightFactUnits
    case weightUnits
}
